package net.tcs.core;

public enum TCSCommandType {
    COMMAND_BEGIN_JOB,
    COMMAND_RECOVER_JOB,
    COMMAND_TASK_COMPLETE,
    COMMAND_TASK_FAILED,
    COMMAND_TASK_RETRY,
    COMMAND_ROLLBACK_JOB,
    COMMAND_TASK_ROLLBACK_COMPLETE,
    COMMAND_TASK_ROLLBACK_FAILED;
}
